FROM handsonsecurity/seed-ubuntu:large

# Update package lists and install tools
RUN apt update && \
    apt install -y nmap hydra slowhttptest python3-venv golang-go && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*